(load "~/.config/emacs/init.el")
(load (expand-file-name "init.el" user-emacs-directory))
(setq package-enable-at-startup nil)
(menu-bar-mode -1)
(tool-bar-mode -1)
(scroll-bar-mode -1)
(setq inhibit-startup-message t)
